fix: graal error for private @Property (#8542)
Changes to inject @Property(name = "logger.config") via constructor injection.

Graal 22.3 and Micronaut 3.8.0 was throwing:

```
Caused by: java.lang.NoSuchFieldError: No field 'logbackXmlLocation' found for type: io.micronaut.management.endpoint.loggers.impl.LogbackLoggingSystem
195	at io.micronaut.core.reflect.ReflectionUtils.lambda$getRequiredField$2(ReflectionUtils.java:294)
196	at java.base@17.0.5/java.util.Optional.orElseThrow(Optional.java:403)
197	at io.micronaut.core.reflect.ReflectionUtils.getRequiredField(ReflectionUtils.java:294)
198	at io.micronaut.context.AbstractInitializableBeanDefinition.setFieldWithReflection(AbstractInitializableBeanDefinition.java:979)
199	... 113 common frames omitted
```