protect agains activeListener NPE (#10114)
see: https://ge.micronaut.io/s/bixblaqnbdlek/tests/task/:test-suite-netty-ssl-graalvm:test/details/example.micronaut.HelloControllerTest?top-execution=1

java.lang.NullPointerException: Cannot invoke "java.util.List.iterator()" because "this.activeListeners" is null
	at io.micronaut.http.server.netty.NettyHttpServer.stopInternal(NettyHttpServer.java:644)
	at io.micronaut.http.server.netty.NettyHttpServer.bind(NettyHttpServer.java:576)
	at io.micronaut.http.server.netty.NettyHttpServer.start(NettyHttpServer.java:287)
	at io.micronaut.http.server.netty.NettyHttpServer.start(NettyHttpServer.java:104)
	at io.micronaut.test.extensions.AbstractMicronautExtension.beforeClass(AbstractMicronautExtension.java:331)
	at io.micronaut.test.extensions.junit5.MicronautJunit5Extension.befo