build: upgrade H2 for CVE-2022-23221 (#7000)
* Upgrade H2 for CVE-2022-23221 

Hello,

As per [CVE-2022-23221](https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2022-23221), we should update H2 to at least `2.1.210`. 

The dependency cannot be overridden via the build system because Micronaut explicitly queries H2 to get its compatibilities and fails:

```
io.micronaut.context.exceptions.BeanInstantiationException: Bean definition [javax.sql.DataSource] could not be loaded: 
Unable to determine H2 compatibility mode
-----------------------------------------
SQL State  : 42001
Error Code : 42001
Message    : Syntax error in SQL statement "SELECT [*]VALUE FROM INFORMATION_SCHEMA.SETTINGS WHERE NAME = 'MODE'"; expected "TOP, DISTINCT, ALL, *, INTERSECTS, NOT, EXISTS, UNIQUE, INTERSECTS"; SQL statement:
SELECT VALUE FROM INFORMATION_SCHEMA.SETTINGS WHERE NAME = 'MODE' [42001-210]
```

Therefore the fix is needed in Micronaut itself.

* Update test